export const FETCH_TODO_REQUEST = "FETCH_TODO_REQUEST";
export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS";
export const FETCH_TODO_FAILURE = "FETCH_TODO_FAILURE";


export const SEARCH_TODO_REQUEST = "SEARCH_TODO_REQUEST";
export const SEARCH_TODO_SUCCESS = "SEARCH_TODO_SUCCESS";
export const SEARCH_TODO_FAILURE = "SEARCH_TODO_FAILURE";